Pocket/recommendation-api

app/json/slate_config.schema.json, app/json/slate_configs.json, app/json/slate_lineup_config.schema.json, app/json/slate_lineup_configs.json, app/json/utils.py
This is the squashed and signed commit of another branch that has already been PR'd (https://github.com/Pocket/recommendation-api/pull/206):
Added GUID checks to schema
Removed duplicated slates
Added Anrdoid Discover slates and lineup
=> Signing all the commits

.github/dependabot.yml
Match our other repositories that get dependabot daily updates
=> chore(depbot): matching other repos

app/json/slate_lineup_configs.json
This adds the personalized topic slate lineup for Android.
=> Android discover personalized topic lineup

.aws/src/main.ts
Update service request count alarm per SLA https://getpocket.atlassian.net/wiki/spaces/PE/pages/1626243081/RecommendationAPI+SLA
=> update service alarms per defined SLA

app/json/slate_lineup_configs.json
Matches the Android Discover experience right now
=> iOS SlateLineupID

app/json/slate_config.schema.json, app/json/slate_configs.json
Merge into https://github.com/Pocket/recommendation-api/pull/373 if this case is an improvement.
=> Make case consistent

buildspec.yml
Fix install command in buildspec now that we've switch to an Alpine image. https://github.com/Pocket/shared-infrastructure/pull/229
=> Fix buildspec command

.github/CODEOWNERS
Improve workflows by changing up codeowners
=> Update codeowners to reflect responsibilities

.aws/src/main.ts
Backend doesn't belong on call for this repo
=> Put jesh on call for recommendations-api

app/main.py
Sentry asked us to disable tracing so we dont pay more $$$>
=> removing sentry tracing

app/graphql/graphql_router.py
The mock data for `setupMomentSlate` should have unique identifiers. This is only used in development at the moment.
=> Make mock data more realistic for CorpusSlate

.github/CODEOWNERS
Make @Pocket/dataproducts code owner of this repo, such that @lfishhead can review changes, and we can move faster on PRs.
=> Make @pocket/dataproducts code owner

.aws/cdktf.json, .aws/package-lock.json, .aws/package.json, .aws/src/dynamodb.ts, .aws/src/main.ts, .aws/src/sqsLambda.ts, buildspec.yml
=> chore(pagerduty): Add a runbook to the alarm

.docker/localstack/dynamodb/recommendation_api_metadata_data.json, .run/main.run.xml, docker-compose-local.yml, docker-compose-python-macosbigsur.yml, docker-compose.yml, tests/assets/topics.py, tests/functional/test_dynamodb_base.py
Make tests run reliably. The change that fixed the flaky tests was to remove the localstack volume from docker-compose.yml.
Additional changes:
- Include `corpus_topic_id` for local development in [.docker/localstack/dynamodb/recommendation_api_metadata_data.json](https://github.com/Pocket/recommendation-api/pull/936/files#diff-dfd044ffa99c9bc722ec94fb81ce13a3dcd11143ddb5f1ece3c19a11547a6e83)
- Add [docker-compose-local.yml](https://github.com/Pocket/recommendation-api/pull/936/files#diff-aed91aa2667654a05077a027349bdccf0caa1bfefddc15a397fc00f1ee8385d3) to start Docker with dummy data initialized by localstack.
Error message:
> botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the CreateTable operation: Cannot create preexisting table
- …
=> fix(tests): "Cannot create preexisting table" error 

app/graphql/resolvers/corpus_slate_lineup_resolvers.py
Fix ['Unclosed client' error](https://sentry.io/organizations/pocket/issues/3696851013/events/ece585fad96e4e288bd108cfa27822ff/?environment=production&project=5503693&query=is%3Aunresolved&referrer=issue-stream):
> Unclosed client session
> client_session: <app.data_providers.PocketGraphClientSession.PocketGraphClientSession object at 0x7fc18f47d640>
I don't think this has any user impact, but it does eat into our Sentry quota.
=> fix(Home): Unclosed client session

app/graphql/syndicated_article.py
The intention is to get this https://www.apollographql.com/docs/federation/entities-advanced#compound-keys to be able to resolve publisherUrl
=> Try generating compound key for syndicated article

app/data_providers/item2item.py
We will try to switch it to Apollo caching later.
=> Add quick caching for related recs

app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/recommended_reads_slate_provider.py, tests/functional/graphql/test_home_slate_lineup.py
End the Thompson sampling experiment and put everyone in the treatment.
* [Result summary](https://getpocket.atlassian.net/wiki/spaces/CP/pages/2900328449/Thompson+Sampling+Results)
* [Experiment dashboard](https://app.mode.com/getpocket/reports/955892efcbf4)
=> feat(Home): End Thompson sampling experiment

app/data_providers/item2item.py, tests/functional/graphql/test_related.py
Fix recommending outdated news in Reader mode and for Firefox on-save.
It turned out we cannot rely on the time-sensitive flag to identify evergreen content, so I have to add a hard filter.
Tickets:
* [jira](https://getpocket.atlassian.net/browse/TDP-351)
- use 90 days as a time window that seems reasonable not to recommend too outdated content but still preserve some content pool (~2.5K items)
- keep recommendations on the syndicated page as is because of obligations with the publishers, also the syndicated articles are supposed to be evergreen. Some publisher-based articles might be old though
- we use first_parsed_date as a timestamp in Qdrant, which seems to be the most reliable way to estimate the article's publishing date, it can be way off of course.
=> Use only recent articles for non-syndicated similar recs

.aws/src/main.ts
Avoid spikes in latency on Recommendation API such as happened on May 8th 5:33 am.
- [Jira ticket](https://getpocket.atlassian.net/browse/DIS-675)
- Alert on Slack
- I don't immediately see the root cause. This was something quick I thought we could try. Further investigation is needed if this starts happening more frequently.
Latency spike at 5:30 AM PST corresponded with an increase in requests.
Request increase seems to correspond with latency increase.
=> fix(ECS): Increase minimum task count

app/data_providers/model_loading.py, app/recommenders/hybrid_cf.py
- Make sure the RecAPI doesn't crash if the HybridCF model suddenly becomes too large for the current setup
- Make model loading optional to still serve the default recs if something went wrong with the model in s3. Other functionality of RecAPI should also work
@chidamnat Let's do a code freeze on Metaflow side for the `v1` model. If we want to improve it let's introduce `v2` and then we'll go through testing again before redeploying it. Even though we'll have some guardrails there shouldn't be any surprises on RecAPI side regarding the updated model. It should be exactly the same setup as was tested during the deployment.
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/DIS-755)
=> Add more guardrails for hybrid CF model loading

.aws/src/main.ts
Stop showing code deploy notifications, which were showing up in #content-alerts, and are not needed.
=> chore: remove code deploy notification

app/translations/en-US/home.json
=> fix(translations): updating pocket-worthy

app/data_providers/slate_providers/pride_slate_provider.py, app/translations/de-DE/home.json, app/translations/en-US/home.json
Add a more link to the collection page for the pride slate
=> fix(more): adding in a more link for the pride slate

.aws/src/config/index.ts, .aws/src/dynamodb.ts, .aws/src/elasticache.ts, .aws/src/main.ts, .aws/src/monitoring.ts, .aws/src/sqsLambda.ts
=> fix(tags): adding in cost center tags

app/config.py, app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/topic_slate_provider.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, tests/functional/graphql/test_home_slate_lineup.py, tests/unit/data_providers/test_for_you_slate_provider.py, tests/unit/data_providers/test_home_dispatch.py
Re-add collections to home and remove the paths for Pride https://mozilla.slack.com/archives/C064WL2KT2M/p1720719226160049
https://mozilla-hub.atlassian.net/browse/POCKET-10236
=> feat(collections): re-add collections into Pocket Home

app/config.py, tests/functional/graphql/test_home_slate_lineup.py
Remove self-improvement since its also in LifeHacks slates
=> fix(self-improvement): remove self improvement for now

.circleci/config.yml
Test out an updated aws-ecr orb. We will move this over to the shared Pocket orb once we're tested it in production.
Tickets:
* [MC-1550](https://mozilla-hub.atlassian.net/browse/MC-1550)
[MC-1550]: https://mozilla-hub.atlassian.net/browse/MC-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade CircleCI deprecated Linux images
