app/cache.py, tests/unit/cache/test_json_serializer_with_none_token.py
Fix this error: https://sentry.io/organizations/pocket/issues/2239906077/events/19db96fd94f9465b959434e10525b21b/
Slack thread:
* https://pocket.slack.com/archives/C01CKCB9746/p1615221053001800
- From the Sentry stack trace, it's not clear to me how the code can get in a state where dumps() receives a NoneValue. I guess there's an assumption built into aiocache that outputs from `loads` can be fed into `dumps`.
=> [SHIPIT-123] Cache serializers dumps NoneValue

README.md
Avoid confusion in ReadMe, by removing a Confluence link that is not accessible publicly.
=> [SHIPIT-123] Remove internal Confluence link from Readme

app/main.py, app/models/slate_config.py, app/models/slate_lineup_config.py, tests/assets/json/invalid_slate_configs.json, tests/assets/json/invalid_slate_lineup_configs.json, tests/functional/json/slate_lineup_config.py, tests/functional/models/test_slate_config_model.py, tests/functional/models/test_slate_lineup_config_model.py
Check configs to make sure GUIDs used by Slates and SlateLineups are unique.
Based on PR feedback I did the following:
* Moved slate and lineup validation code into their respective models. This means we do the validations on model load, which is probably right so we don't end up with invalid models being loaded
* Cross GUID checks (between slate and lineup) done at app start.
* Tests
=> Check that GUIDs are unique

app/json/slate_configs.json, app/json/slate_lineup_configs.json
adding initial slate lineup and required slates for web home experiment.
The doc i am following is [here](https://docs.google.com/document/d/1dmb4Dk4OY95BgJ_R2upnZ9i1z5gCED347THtc0Dv21w/edit?usp=sharing)
The slates that are included are:
- curated self-improvement
- curated food
- curated technology
- all collections slate (each candidate is a collection)
- [10 Incredible Long-Reads That’ll Transport You to Another Time and Place](https://blog.getpocket.com/2020/04/10-incredible-long-reads-thatll-transport-you-to-another-time-and-place/)
- [how to cook](https://getpocket.com/explore/item/how-to-cook)
These are all in the web home test #1 slate lineup
=> adding initial lineup for web home experiment

app/json/slate_lineup_configs.json, tests/functional/json/slate_lineup_config.py
The Web repo assumes that topic linups have a curated and algorithmic slate, in this order. Whether clients can depend on slates coming in a particular order is a great question, that we should talk about.
=> [SHIPIT-123] Fix topic slate order

.docker/localstack/dynamodb/recommendation_api_candidate_sets_data.json, app/config.py, app/json/slate_config.schema.json, app/json/slate_configs.json, app/json/slate_lineup_configs.json, app/main.py, app/models/candidate_set.py, app/models/recommendation.py, app/models/slate.py, app/models/slate_lineup.py, tests/assets/json/recit_response.json, tests/functional/models/test_candidate_set_model.py, tests/functional/models/test_slate_model.py, tests/unit/models/test_candidateset_model.py
This adds a new type of CandidateSet, a `RecItCandidateSet`, which allows us to make slates that use RecIt as the source of items. This specifically allows for personalized slates using the bestof, curated, or syndicated corpora. Once the vector store exists we would move this functionality there, but there isn't any timeline on that work currently. This allows us to test out the performance of personalized slates sooner.
See the [design doc](https://docs.google.com/document/d/14PaPC3xtG7ajdH7U5VguO3J-ePoUIp5Egm2EBkWYd-M/edit) for more details.
* Created a `DynamoDBCandidateSet` for the existing `CandidateSetModel` functionality
* You can now specify a `RecItCandidateSet` as `recit-personalized/bestof` (or `curated` or `syndicated`) in a slate.
* If a user doesn't have a profile we return …
=> Add RecIt CandidateSet Support

app/models/clickdata.py, app/models/recommendation.py, app/models/slate.py, app/models/topic_recommendations.py, tests/functional/models/test_clickdata_model.py
Get clickdata by slate id, instead of using topic-based clickdata by default.
Tickets:
* https://getpocket.atlassian.net/browse/BACK-680
- This is based on https://github.com/Pocket/recommendation-api/pull/221, but we wanted to split in two:
1. Get clickdata by slate_id (this PR)
2. Remove the old topics graphQL endpoint (blocked by the Web repo removing references)
=> [BACK-680] Switch the format of the click data input to the new source

.docker/localstack/dynamodb/recommendation_api_candidate_sets_data.json, app/config.py, app/graphql/graphql.py, app/json/slate_config.schema.json, app/json/slate_configs.json, app/json/slate_lineup_configs.json, app/main.py, app/models/candidate_set.py, app/models/recommendation.py, app/models/slate.py, app/models/slate_lineup.py, tests/assets/json/recit_response.json, tests/functional/models/test_candidate_set_model.py, tests/functional/models/test_slate_model.py, tests/unit/models/test_candidateset_model.py
This re-applies https://github.com/Pocket/recommendation-api/pull/218 and fixes some deployment issues. I flagged the changes between these two commits since you can't really tell from this what was done.
=> Reapplies RecItCandidateSet Support and fixes the deployment breaks.

app/models/slate.py, app/models/slate_lineup.py, tests/functional/models/test_slate_lineup_model.py, tests/unit/models/test_slate_model.py
Deduplicate recommendations across slates in a lineup. If a recommendation occurs more than once, it's removed from all but the first slate.
Tickets:
* https://getpocket.atlassian.net/browse/BACK-683
- test_slate_lineup_model is almost at a point where a fixture library would be convenient, but I think it's still manageable for now.
=> [BACK-683] Dedupe recs

app/json/slate_configs.json
Disable Thompson sampling on the Coronavirus slate.
Slack thread:
* https://pocket.slack.com/archives/C01CKCB9746/p1615591932046400?thread_ts=1615591370.044400&cid=C01CKCB9746
=> Remove Thompson sampling from Coronavirus slate

app/rankers/algorithms.py, tests/unit/rankers/test_algorithms.py
For some reason we are generating negative parameters for our beta distribution for module priors. This is not valid. If we find invalid module level priors just use the naive default.
=> Don't use invalid MLE priors for modules

app/json/slate_config.schema.json, app/json/slate_configs.json, app/json/slate_lineup_configs.json, app/rankers/__init__.py, app/rankers/algorithms.py, tests/unit/rankers/test_algorithms.py
The Web client isn't getting enough recommendations. It needs at least 20. We accomplish this in two ways:
1. Limit curated nonsyndicated to 5, to prevent too many duplicates from being removed from the second slate.
2. Remove the top15 experiment from 'All Curated New Tab', so it can reliably return at least 15 recommendations.
Slack thread:
- https://pocket.slack.com/archives/CR6T8BNCT/p1617924164014300
We created a slate 48e766be-5e96-46fb-acbf-55fee3ae8a28 based on 2e3ddc90-8def-46d7-b85f-da7525c66fb1 because Ian said the latter is used elsewhere, where we don't want to limit to 5 recommendations.
=> [SHIPIT-123] Fix explore homepage lineup

app/json/slate_configs.json
Editorial team would like more control over content of curated section of topic pages during tests with new tab in Q2.
Removing Thompson sampling from the curated sections of the explore topic pages will revert to approval based ordering and allow them to provide excerpts in the tiles on new tab that correspond predictably to the items appearing in the curated section of those pages.
No changes to algorithmic slates.
Slack thread: https://pocket.slack.com/archives/CN0L1NDD3/p1618511471008400
Removed Thompson sampling ranker from curated topic slates.  
Alternative would be to set up separate curated topic slates with TS enabled.
=> removing thompon sampling from curated topic slates

.aws/src/sqsLambda.ts
I noticed that we were constantly getting non-critical alarms for the translation function. When looking in sentry there were no issues, but when looking at the logs, it looks like we are hitting the lambda timeout. 
My guess is that this is occurring because larger candidate sets are being created. Lets see if a timeout increase fixes this, I arbitarly chose 120 seconds which is 4x the current timeout.
=> fix(lambda): increase timeout

.aws/package-lock.json, .aws/package.json, .aws/src/elasticache.ts, .aws/src/main.ts
Update pocket/terraform-modules to 1.19.1 to pull in [a fix for the request count alarm action](https://github.com/Pocket/terraform-modules/commit/27c33b53f3b9f624bf41013176372290ef58de6d#diff-0731374296d9e4f7cac42a725e1b58a908e207fd57df2893966c30f7379b0592R849-R850), to make the HttpRequestCount alarm non-critical.
Additionally these changes were made:
- Update portMappings because of a breaking interface change in https://github.com/Pocket/terraform-modules/pull/132.
- Update Elasticache because of a breaking interface change in https://github.com/Pocket/terraform-modules/pull/122.
- Update cdktf and constructs to [match the version used in @pocket/terraform-modules](https://github.com/Pocket/terraform-modules/blob/main/package.json#L41-L42). No impact expected in production, but …
=> Fix alarm action for http request count

app/json/slate_lineup_config.schema.json, app/json/slate_lineup_configs.json, app/rankers/__init__.py
Enable the ranker that personalizes the order of slates in the topic lineup.
Tickets:
* [BACK-801](https://getpocket.atlassian.net/browse/BACK-801)
Follow up from https://github.com/Pocket/recommendation-api/pull/264
=> Add personalized topics ranker to topic lineup

app/json/slate_configs.json
Update the slate displayNames to something useable by Android. For the topics I just use the topic name. For collections I used the copy from web home.
This is potentially blocking a test release for the week after wellness so @marcin-kozinski requested we get the change out today.
I've confirmed with web that they don't use these fields, so there shouldn't be any impact to them.
=> Update slate displayNames for Android

app/models/metrics/abstract_metrics_factory.py
Avoid confusion in Sentry caused by duplicate error messages. An error with almost exactly the same information is logged on line 51.
A secondary goal is to lower cost in Sentry by removing unnecessary errors.
Slack thread:
* https://pocket.slack.com/archives/C01CKCB9746/p1627317161003700
Example Sentry errors:
* [Error from line 51](https://sentry.io/organizations/pocket/issues/2535109173/events/b2c9ecf42531491d89a48d76dc9566ed/?project=5503693)
* [Error from line 124](https://sentry.io/organizations/pocket/issues/2535109179/events/ea41a0976d034cc3ad3c509285605c5c/?project=5503693)
- There are situations where it's expected that a DynamoDB batch_get_item request returns no items, for example if the last chunk only contains 1 key, and that key is new. So it makes sense to turn this error …
=> Change duplicate error to info

app/json/slate_configs.json, app/models/slate.py
We want to get some confidence that the engagement pipeline works end-to-end. The approach I'd like to take is to create QA slates for which we can control exactly how many impressions and opens it's gets, because only a particular QA user will see it. This will allow us to track this QA slate using its unique slate id through the engagement pipeline.
Tickets:
* https://getpocket.atlassian.net/browse/HOMPER-10
Documentation:
* https://docs.google.com/document/d/1AHAIdKrgDLPgUgUVoziqnX9vgnFyASBZQ595y3Oqvkk/edit#heading=h.o31clnk4jx7l
QA user details:
* https://pocket.slack.com/archives/C03QVL4SU/p1627576490339900
- This change is intended to be temporary. Once the end-to-end QA is complete, we can revert this change.
- A better long-term solution would be to use Unleash for deciding which …
=> Create QA slates that are served to a QA user

app/config.py, app/models/slate.py, tests/functional/models/test_slate_lineup_model.py
Fix https://github.com/Pocket/recommendation-api/pull/317, that only got applied to the getSlate operation. Clients are actually making a getSlateLineup request.
The end goal is still to get confidence that the engagement pipeline works end-to-end, by tracking a QA slate through the pipeline. By only serving this QA slate to a QA user, we can control exactly how many impressions and opens it gets.
Request:
```shell
curl --location --request POST 'https://recommendation-api.getpocket.dev' \
--header 'userId: 47372502' \
--header 'Content-Type: application/json' \
--data-raw '{
"query": "query QueryQA {\n getSlateLineup(slateLineupId: \"af3a5196-be16-4bf7-b131-70981e43b132\") {slates { id }\n }\n}",
"variables": null,
"operationName": "QueryQA"
}'
```
Response:
```
{
"data": { …
```
=> Serve QA slates for getSlateLineup

app/json/slate_configs.json, app/json/slate_lineup_configs.json
Create initial lineup and slates needed for initial web home experiments.
Lineups are outlined in [PRD](https://docs.google.com/document/d/10WkThCdi7AIeBbZkUOUqWwZ8WjiBwR3ugAb5hSw3z0A/edit?usp=sharing) and described in additional detail [here](https://getpocket.atlassian.net/l/c/ssRP4tfw)
[HOMEPER-24](https://getpocket.atlassian.net/browse/HOMPER-24)
For the fallback lineup for users that don't qualify for personalization I selected 
- three topic slates to be consistent with the personalized lineup and 
- picked them based on ~~total new tab CTR~~ consultation with editorial team
These choices should be reviewed with ~~editorial and~~ product.
=> adding fallback slate lineup for web home

app/json/slate_configs.json, app/json/slate_lineup_config.schema.json, app/json/slate_lineup_configs.json, app/models/slate_lineup_config.py, app/rankers/__init__.py, app/rankers/algorithms.py, tests/unit/rankers/test_algorithms.py, tests/unit/utils.py
Add a personalized lineup for the H2 web home work.  The details of the lineups are included [here](https://getpocket.atlassian.net/l/c/WsNaYxD4).  The goal of the work is to allow for lineups to have a mix of topic and non-topic slates and leave the non-topic slates as ordered, and remove the lower ranked topic slates after a cutoff.
* [Details](https://getpocket.atlassian.net/l/c/WsNaYxD4)
* [HOMEPER-25](https://getpocket.atlassian.net/browse/HOMPER-25)
* [HOMEPER-23](https://getpocket.atlassian.net/browse/HOMPER-23)
* [HOMEPER-27](https://getpocket.atlassian.net/browse/HOMPER-27)
We refactored the personalized topic slate ranker to comply with the `topN` style used for truncating candidate sets.  There is now a `top1_topics` ranker used for Android discover and a `top3_topics` ranker …
=> Adding a personalized webhome lineup

app/json/slate_lineup_configs.json
Update slate lineups for web home.  Changes here after discussions between Carolyn, Ian, and MattC:
- three fallback (unpersonalized) topic slates are [business](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2046197833/RecsAPI+Slate+Documentation#Curated-Business-Slate), [health](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2046197833/RecsAPI+Slate+Documentation#Curated-Health-Slate), and [entertainment](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2046197833/RecsAPI+Slate+Documentation#Curated-Entertainment-Slate)
- editor's pick slate for both lineups is [curated without syndicated](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2046197833/RecsAPI+Slate+Documentation#%5BinlineExtension%5DCurated-Live-No-Syndicated)
- stand in slate for unpersonalized lineup …
=> [HOMEPER-23] - updating web home lineups

app/json/slate_lineup_configs.json
create a slatelineup for firefox android home recommendations. 
PRD:
* https://docs.google.com/document/d/1-P-Q15nHMGy_TQuwFh3YW07-dINXB5_rDMocwTuFl5s/edit#heading=h.jyahmgu05z6p (direct link to slates requested for this lineup)
=> slatelineup for firefox android home recommendations

tests/functional/models/test_slate_lineup_model.py
Fix test that would fail 50% of time time, because the order of recommendations was determined using Thompson sampling.
Any ideas to prevent similar mistakes from happening in the future, beyond the comments that I added?
CircleCI:
* https://app.circleci.com/pipelines/github/Pocket/recommendation-api/1511/workflows/a79d0370-c564-4b3d-8617-89a2a844f829/jobs/5841
=> Fix assertion that would fail randomly

app/json/slate_configs.json
The candidate set GUIDs associated with single collection slates were updated [here](https://github.com/Pocket/dl-metaflow-jobs/pull/54) to persist when collection slugs are revised.  The changes need to be reflected in the two current single collection slates exposed in the recommendation-api.  
original sentry errors when slugs changed and candidate sets expired a month after collections-api went live:
https://pocket.slack.com/archives/CA3GZBXNG/p1628634663000700
[slate documentation](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2046197833/RecsAPI+Slate+Documentation#Single-Collection-Slates)
[metaflow PR](https://github.com/Pocket/dl-metaflow-jobs/pull/54)
=> update single collection slates with new candidate set guids

app/models/candidate_set.py, app/rankers/algorithms.py
The warning might end up being way too noisy, so I can be convinced to turn that down to an info or debug, but we've had several times now where we intended to get more items from a CandidateSet than we did, and it has caused issues. 
Long term, we probably need an entire configuration to represent how many items are expected at each stage. I did this in RecIt by having rankers explicitly note the min items they expect. We will probably need to have CandidateSets support limits to allow for us to express the idea that we want a specific number of items at each stage of the pipeline.
=> Fetch more items from RecIt, make top-n rankers warn about insufficient items

.aws/src/sqsLambda.ts
Decrease false-positive alarms for Lambda. This alarm was active for several months without 
Slack thread:
* https://pocket.slack.com/archives/C016NAMSW2J/p1629407675020500
- I increased the threshold to 20, well above the normal level.
- I decreased the period and increased the evaluationPeriods, to prevent a single spike from triggering the alarm, as occurred on Aug 6th.
=> Decrease false-positive alarms for SQS Lambda

app/json/utils.py
Update util to make the printing easier to read. Also includes experiment hashes now, and allows you to limit which lineups are shown.
```
iwsmith@vulcan json % python utils.py --lineup 55
[55f5ed8] Web Home - Curated Topic Slates Not Live on New Tab
└── [2bd35d5] Experiment: default layout
├── [af2cc2c] Slate:  Business
│   └── [817f4b2] Experiment: curated not new tab business items
│       └── [962a8ef] Candidate Set
├── [00f0c59] Slate:  Career
│   └── [3069faf] Experiment: curated not new tab career items
│       └── [651990d] Candidate Set
├── [856eb5f] Slate:  Education
│   └── [8265cfe] Experiment: curated not new tab education items
│       └── [3a5f2bf] Candidate Set
├── [cceefa2] Slate:  Entertainment
│   └── [665f73b] Experiment: curated not new tab entertainment items
│ …
```
=> Update util.py to print more like `tree`

app/json/slate_lineup_configs.json
This enables three new slates in support of an Android PersonalizationV2 experiment:
*control* - We are using a different Lineup ID so I can easily differentiate users in experiment from those not in experiment
*personalized_curated* - A new personalization algorithm that generates more diverse recommendations, only recommends items that went live in the last 52 weeks, and generates more items to decrease the amount of repeats users see.
*personalized_topic* - Selects a single topic to show the user based on their profile, but this time shows them an algorithmic topic slate instead of a curated one.
See https://docs.google.com/document/d/1PSjmTiBWIn_tuweoc5kaAVlsEqgv29ujMFoHVUaU0is/edit#
=> Android Personalization V2

app/json/slate_config.schema.json, app/json/slate_configs.json
Carolyn and @collectedmind have provided new text to describe various slates for web home.  These have been added to slate_configs.json to update the `description` field (which is a required field).  
Previous descriptions of the properties of the slates' items have been moved to an `internal_description` field to add in understanding characteristics of the items the slates contain if viewing the config json.  
[slate names doc](https://docs.google.com/document/d/1Ha6DbbenMrBOm42uVpH7chRqCrpM-MSwwowulCG-mkI/edit?usp=sharing)
Moved old descriptions to new non-required `internal_description` field
=> Updating slate descriptions

.aws/src/main.ts
Fix error during deployment caused by a Dockerhub rate limit:
> CannotPullContainerError: inspect image has been retried 5 time(s): httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/amazon/aws-xray-daemon/manifests/sha256:5bf715bbe434ebf892b66bba54ce04db47b2914f23a949410d8029fbbf...
=> Auth with Docker for XRay image

app/json/slate_lineup_config.schema.json, app/json/slate_lineup_configs.json, app/models/slate_config.py, app/rankers/__init__.py, app/rankers/algorithms.py, tests/unit/rankers/test_algorithms.py
1. Add `rank-topics`, which just re-ranks the topics based on a user profile
2. Updated the Web SlateLineup to use it for the Web Home Personalization experiment
3. Update the Web Home Personalized and Web Home Unpersonalized SlateLineups to return *all* topics. This will allow for filtering to relevant topics on the client. This may cause performance issue, but since the topics are all fairly static the hope is everything is sufficiently cached.
=> Add rank-topics ranker, change Web to use it, add all topics

app/json/slate_configs.json, app/models/slate_lineup_config.py, app/rankers/__init__.py
I missed a location for adding a personalized ranker (see the below sentry error). I centralized this in `rankers/__init__.py` so this doesn't happen again.
https://sentry.io/organizations/pocket/issues/2680882333/?project=5503693&query=is%3Aunresolved
Also remove Thomspson-Sampling from collections, which is unrelated but is necessary to fix collections we think.
=> Register personalized ranker in a second location, remove Thompson-Sampling from collections

buildspec.yml
Fix an error when deploying to dev:
> Error: Error describing SSM parameter (/RecommendationAPI/Prod/SENTRY_DSN): ParameterNotFound:
Slack thread:
* https://pocket.slack.com/archives/CR6T8BNCT/p1632777571023200
- We copied buildspec.yml from the template:
https://github.com/Pocket/backend-typescript-template/blob/main/buildspec.yml
=> Fix dev build

app/json/slate_lineup_configs.json
Basically resets to what we had a few days ago. Pulling all the topic slates is too slow and we aren't able to address that right now.
=> Web Home Personalized top3 topics, only return 3 topics for unpersonalized

Pipfile, Pipfile.lock
Undo automatic upgrade from https://github.com/Pocket/recommendation-api/pull/430. This was causing high error volume in Sentry. See https://github.com/Pocket/recommendation-api/pull/416.
Sentry error:
- https://sentry.io/organizations/pocket/issues/2194211623/?environment=production&project=5503693&query=is%3Aunresolved&statsPeriod=14d
Slack thread:
- https://pocket.slack.com/archives/C03QVL4SU/p1636042691425700
- https://pocket.slack.com/archives/C02KH5U7G79/p1636065358002800
=> Downgrade Uvicorn to 0.14.0 to fix xray errors

aws_lambda/tests/fixtures/lambda_sqs_event.py
Fix Lambda test failing:
```
AssertionError: expires_at 1644006655 should be at least 1644360869.5393023
```
The fixture had `expires_at` set on the wrong object, which caused tests to start failing after February 4, 2022. `expires_at` should be on the candidate set level, not on individual candidates.
CircleCI error:
* https://app.circleci.com/pipelines/github/Pocket/recommendation-api/2313/workflows/663f2a0e-72af-4ed4-8429-e42399b824eb/jobs/9962
- Mocking `time.time()` might be a better way to test this logic, but I'm considering that out-of-scope for now.
=> Fix Lambda tests

app/data_providers/curation_api_client.py, app/data_providers/metrics_client.py, tests/unit/data_providers/test_metrics_client.py
- Fix 'coroutine was never awaited' exception
- Escape GraphQL parameters
1. `source <(maws -o awscli)` and choose `pocket-dev-PocketSSODataLearning`.
2. Select 'main Pocket-Dev' run configuration in Pycharm.
3. Run GraphQL query:
```graphql
query corpus_slate {
getRankedCorpusSlate(slateId: "f99178fb-6bd0-4fa1-8109-cda181b697f6") {
corpusItems {
id
}
}
}
```
=> Corpus thru ranker mathijs

schema.graphql
Fix an issue that prevents `listTopics` from being run through ClientAPI, where it [returns null](https://studio.apollographql.com/graph/pocket-client-api/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABADICWAzigCoQAOZUFRwAOkkUQDaU32PM2HTkTJh2IohS4wA5hJGw8AQxQQ8JZQCMEXBZzCU6XZQQByyxPqI58Ba5QAiRkwQTjhnOstkJqBOgRrWCoIOAAxBHcASQ9OAF92eJB4oA&variant=current) if `query` is included. The root cause is that the GraphQL schema defined a different type than the [topic model](https://github.com/Pocket/recommendation-api/blob/main/app/models/topic.py#L28). The latter has the correct type.
Slack thread:
* https://pocket.slack.com/archives/C02JZ4TRF0S/p1652210619681879
Related PR:
* https://github.com/Pocket/dl-metaflow-jobs/pull/80
This query is deprecated, but still in use in Metaflow. …
=> Fix `Topic.query` mismatch between code and schema

tests/functional/graphql/test_get_ranked_corpus_slate.py
Disable a test that has suddenly starting to fail, and are not testing code that is in production. The test fails locally and [in CircleCI](https://github.com/Pocket/recommendation-api/pull/862).
We _think_ these tests might be hitting production GraphQL endpoints? If so, we should discuss whether to mock out external dependencies, to ensure tests can run reliably in isolation.
=> Skip test_get_corpus_slate

app/models/user_impressed_list.py
Android request to recs-api is raising personalization error and failing to return any recommendations to android discover.
[slack](https://pocket.slack.com/archives/C013MQ3NBN1/p1654545815622619)
remove raising of personalization error for users without impressed items
=> fix for android lineup

app/graphql/graphql_router.py, app/graphql/update_user_recommendation_preferences_input.py, app/graphql/update_user_recommendation_preferences_mutation.py, app/graphql/user_recommendation_preferences.py, schema.graphql, tests/assets/topics.py, tests/functional/graphql/test_recommendation_preference_topics.py, tests/functional/graphql/test_setup_moment_slate.py, tests/functional/graphql/test_update_user_recommendation_preferences.py
1. Rename `UserContentProfile` to `UserRecommendationPreferences` to reflect the spec: https://github.com/Pocket/spec/pull/144/commits/54c92f057625fc6bdc950f2fffe7cf44bf3d5d59, based on suggestion from Matt C.
2. Remove `contentProfile` from `User` until we're ready to implement it. Clients won't need to fetch user preferences for v0 of the experiment, so this might be a while out.
3. Add functional tests
4. Make the mock ids in the `setupMomentSlate` unique to make the mock data more realistic.
- Spec PR: https://github.com/Pocket/spec/pull/144
- [Slack](https://pocket.slack.com/archives/C01VDFM30J2/p1654542205108089?thread_ts=1653442540.283049&cid=C01VDFM30J2)
```graphql
query TestPreferenceTopics {
recommendationPreferenceTopics {
id
name
}
}
mutation TestUpdateTopics { …
```
=> Rename setup moment endpoints

app/data_providers/topic_provider.py, app/data_providers/user_recommendation_preferences_provider.py, app/graphql/graphql_router.py, app/graphql/update_user_recommendation_preferences_mutation.py, app/models/topic.py, tests/assets/json/user_recommendation_preferences.json, tests/assets/topics.py, tests/functional/graphql/test_recommendation_preference_topics.py, tests/functional/graphql/test_setup_moment_slate.py, tests/functional/graphql/test_topic_metadata_graphql.py, tests/functional/graphql/test_update_user_recommendation_preferences.py, tests/functional/models/test_topic_metadata_model.py, tests/mocks/topic_provider.py, tests/unit/data_providers/test_user_recommendation_preferences_provider.py
Allow user recommendation preferences to be fetched by implementing `UserRecommendationPreferencesProvider.fetch`.
Additional changes:
- Move methods from `TopicModel` to `TopicProvider` that fetch topics from DynamoDB. This is part of moving to the [data mapper pattern](https://en.wikipedia.org/wiki/Data_mapper_pattern).
- Simulate `corpus_topic_id` being stored in DynamoDB, to make sure that we can add a column to the topic DynamoDB table without breaking anything. In the next PR, I'll add this field to the model and use it for ranking.
- Clean up tests a bit:
- Use accurate topic ids in `tests/assets/topics.py`
- Remove patches for `aiohttp.ClientSession.get` where its unused
- Replace fixture code in tests with imported fixtures
Jira issue:
- …
=> [HS-43] Setup moment fetch preferred topics

app/data_providers/dispatch.py, app/graphql/corpus_slate.py, app/graphql/graphql_router.py, app/graphql/util.py, tests/functional/graphql/test_setup_moment_slate.py, tests/unit/graphql/test_get_field_argument.py
Allow clients to limit the number of recommendation that `setupMomentSlate` returns.
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/HS-62)
- As far as I can tell, Graphene does not make it easy to access field arguments, so I wrote a utility function for this.
=> [HS-62] Allow clients to limit recommendation count in setupMomentSlate

.aws/src/main.ts, app/data_providers/dispatch.py, app/data_providers/user_recommendation_preferences_provider.py, tests/unit/data_providers/test_user_recommendation_preferences_provider.py
- [HS-63](https://getpocket.atlassian.net/browse/HS-63) When calling `setupMomentSlate`: an error occurred "'NoneType' object is not subscriptable". This happened when the user did not have a record in the feature group with user recommendation preferences.
- [HS-65](https://getpocket.atlassian.net/browse/HS-65) When calling `updateUserRecommendationPreferences`: "an error occurred (AccessDeniedException) when calling the PutRecord operation." This happens because RecommendationAPI did not have access to `sagemaker:PutRecord` on the feature group with user recommendation preferences.
- We've started a strategy of creating shared policies for services, but RecommendationAPI doesn't contain this policy yet. Unless someone feels strongly, I'd prefer to keep applying the [principle of least …
=> [HS-63][HS-65] Fix Setup Moment bugs

app/data_providers/dispatch.py, tests/assets/json/corpus_candidate_sets.json, tests/unit/data_providers/test_corpus_feature_group_client.py
1. Change the Setup Moment Corpus candidate set to the editorial selected content one created in [#92](https://github.com/Pocket/data-flows/pull/92).
2. Change the CorpusSlate id field from a static value to a random uuid, per decision in [#147](https://github.com/Pocket/spec/pull/147/files). (It was previously set to the candidate set id as an oversight.)
I confirmed the new record is available using the aws cli:
```shell
aws sagemaker-featurestore-runtime get-record --feature-group-name production-corpus-candidate-sets-v1 --record-identifier-value-as-string 57d544d6-0758-4cd1-a7b4-86f454c8eae8
```
Ticket: https://getpocket.atlassian.net/browse/HS-82
Jira thread where decision was made to end the current experiment:
- https://pocket.slack.com/archives/C03AGDGJ1E0/p1657239584911799?thread_ …
=> Change setup moment corpus candidate set and corpus slate id

app/data_providers/dispatch.py, app/data_providers/snowplow/snowplow_corpus_slate_tracker.py, app/graphql/graphql_router.py, app/graphql/user_middleware.py, app/models/user.py, tests/functional/data_providers/test_snowplow_corpus_slate_tracker.py, tests/functional/graphql/test_setup_moment_slate.py, tests/mocks/user.py
The Dbt model that G created looks for `hashed_user_id` or `hashed_guid` to be passed into the Snowplow [user entity](https://console.snowplowanalytics.com/cf0fba6b-23b3-49a0-9d79-7ce18b8f9618/data-structures/7d9b5dadf4636e0818411c215770fd3090cb1c226480588fd72c237e89ca9895). Most client events only include the hashed user id, and it's therefore easier to join against these events if  the hashed_user_id is included.
1. Start RecommendationAPI locally using the `main Pocket-Dev` run configuration.
2. Perform a `setupMomentSlate` query:
```shell
curl --location --request POST 'http://localhost:8000' \
--header 'userId: 12345678' \
--header 'encodedId: hashed-12345678' \
--header 'Content-Type: application/json' \
--data-raw '{
"query": "query PostmanSetupMomentSlate { setupMomentSlate{ id …
```
=> Pass hashed user id and guid into Snowplow user entity

app/data_providers/dispatch.py, app/data_providers/snowplow/config.py, app/data_providers/snowplow/snowplow_corpus_slate_tracker.py, app/models/corpus_slate_model.py, tests/functional/graphql/test_setup_moment_slate.py, tests/mocks/corpus_slate_model.py
Add a `recommended_at` field to CorpusSlate that indicates the time at which the corpus slate was recommended. This implements https://github.com/Pocket/spec/pull/152.
Spec change:
* https://github.com/Pocket/spec/pull/152
Jira ticket:
* https://getpocket.atlassian.net/browse/HS-99
=> Add recommended_at attribute to corpus_slate entity

app/models/metrics/abstract_metrics_factory.py
Stop flooding sentry with events for which there is no action.
=> Warn not error on missing item/slate dynamodb metrics

app/data_providers/user_recommendation_preferences_provider.py, app/graphql/update_user_recommendation_preferences_mutation.py, app/models/user_recommendation_preferences.py, tests/assets/json/user_recommendation_preferences_v2.json, tests/functional/graphql/test_update_user_recommendation_preferences.py, tests/unit/data_providers/test_user_recommendation_preferences_provider.py, tests/unit/data_providers/test_user_recommendation_preferences_provider_v2.py
To allow clients to query a User's recommendation preferences, we want to extend the GraphQL User with a `recommendationPreferences` field. https://github.com/Pocket/spec/pull/159 The GraphQL `User.id` field is the _hashed_ user id, while our feature group currently keys preferences on the _integer_ user id (which is deprecated). To extend the GraphQL User object we need to key these preferences on the _hashed_ user id.
Phases:
1. **(This PR) Write preferences to two Feature Groups, keyed respectively on integer user id and hashed user id. [HS-131](https://getpocket.atlassian.net/browse/HS-131)**
2. Backfill from feature group v1 to v2. [HS-132](https://getpocket.atlassian.net/browse/HS-132)
3. Recommendation API reads from v2 keyed on hashed user_id. …
=> [HS-131] Write user preferences keyed on hashed user_id

.circleci/config.yml
Fix Lambda [deployment error](https://app.circleci.com/jobs/github/Pocket/recommendation-api/16628?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
> Usage: pipenv lock [OPTIONS]
> Try 'pipenv lock -h' for help.
> 
> Error: No such option: -r
Pipenv changelog:
* https://github.com/pypa/pipenv/blob/main/CHANGELOG.rst#removals-and-deprecations
CircleCI error:
* https://app.circleci.com/pipelines/github/Pocket/recommendation-api/3565/workflows/f0dfda56-90e7-4551-8f2a-c33a90893a11/jobs/16628
- Lock pipenv to the current version to avoid breaking changes going forward.
=> fix(lambda): Fix breaking change in pipenv and lock pipenv

app/data_providers/dispatch.py, app/data_providers/slate_providers/personalized_for_you_slate_provider.py, app/data_providers/slate_providers/topic_slate_provider.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, app/models/corpus_slate_model.py, tests/functional/graphql/test_home_slate_lineup.py
When a user has set preferred topics, they should see personalized topic slates.
* **Performance optimizations:** There is a [separate Jira ticket](https://getpocket.atlassian.net/browse/HS-192) to perform load testing and get performance in line with the SLA.
* **Requirements possibly not finalized:** There are some outstanding questions in the [Content Requirements doc](https://docs.google.com/document/d/15gBxnXlsKTgGyjZe72VUc43aK9ZoAArP9NaJDNLIaps/edit#heading=h.mljabq907ibf). We might have to come back and add some rankers if requirements are added, but I don't want to get blocked by that.
* **Impression capping:** Captured in [HS-203](https://getpocket.atlassian.net/browse/HS-203).
Requirements
- [Figma Design](https://www.figma.com/file/jawk2lhpNJZZWSJqE3DuNn/Unified-Home-Experiments …
=> feat(Home): Add personalized Home slates

app/graphql/graphql_router.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, app/graphql/resolvers/corpus_slate_lineup_slates_resolver.py, app/graphql/resolvers/legacy/slate_lineup_resolver.py, app/graphql/resolvers/user_recommendation_preferences_resolvers.py, app/models/corpus_recommendation_model.py
Minor cleanup of the GraphQL schema:
- Increase default Home slate count from 10 to 15, to meet the product requirement that [all topic slates will be shown](https://docs.google.com/document/d/15gBxnXlsKTgGyjZe72VUc43aK9ZoAArP9NaJDNLIaps/edit) that the user selects.
- Make some types required that were accidentally marked as optional before.
- Deprecate `setupMomentSlate`.
- [Proposal on Confluence](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2805923841/Recommendation+API+-+Minor+cleanup)
- We agreed to create a proposal even for minor changes like this.
=> Home minor graphql changes

app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/slate_provider.py, tests/functional/graphql/test_home_slate_lineup.py
Restore 'Update your topics' link that was accidentally removed as part of the refactor in https://github.com/Pocket/recommendation-api/pull/958. The cause is that the 'For You' slate stopped returning `recommendationReasonType`.
Tickets:
* https://getpocket.atlassian.net/browse/HS-300
- I don't really like the pattern of duplicating `CorpusSlate` fields as properties. Maybe a better pattern is to pass the CorpusSlate object to a method `set_slate_specific_fields` that can be overridden to set any optional attribute such as `more_link`, `subheadline`, and `recommendation_reason_type`.
=> fix(Home): Restore missing 'Update your topics' link (HS-300)

app/data_providers/snowplow/config.py
Fix an [error](https://sentry.io/organizations/pocket/issues/3436829509/?environment=production&project=5503693&query=is%3Aunresolved#request) where Snowplow responds with a 414 Uri Too Long status.
This probably happens because by default, it encodes the payload as URL parameters in a Get request. Switching to Post should fix this.
Unfortunately, this error did not occur in Snowplow Micro or Snowplow Mini, which both successfully validated the event. It seems to only occur in production, for some reason.
Tickets:
* https://getpocket.atlassian.net/browse/HS-301
Sentry:
* https://sentry.io/organizations/pocket/issues/3436829509/?environment=production&project=5503693&query=is%3Aunresolved#request
Set `buffer_size` to 1 to ensure all events are sent, without having to flush the buffer when …
=> fix(Home): 414 error occurs on Snowplow slate lineup event (HS-301)

app/data_providers/slate_providers/life_hacks_slate_provider.py, app/data_providers/slate_providers/pocket_hits_slate_provider.py, tests/unit/data_providers/test_pocket_hits_slate_provider.py
Update Home content experiment copy. [Carolyn says](https://pocket.slack.com/archives/C03JSA26QGP/p1666734649834359?thread_ts=1666728842.406359&cid=C03JSA26QGP) the accurate copy is:
Life Hacks
Tips for better living
Today's Pocket Hits
Weekday, Month date
* [Jira ticket](https://getpocket.atlassian.net/browse/HS-351)
* [Design](https://www.figma.com/file/jawk2lhpNJZZWSJqE3DuNn/Unified-Home-Experiments)
* [Slack thread](https://pocket.slack.com/archives/C03JSA26QGP/p1666734649834359?thread_ts=1666728842.406359&cid=C03JSA26QGP)
=> fix(Home): Correct copy on Pocket Hits and Life Hacks [HS-351]

app/data_providers/dispatch.py, app/data_providers/snowplow/entities.py, app/data_providers/snowplow/snowplow_corpus_slate_lineup_tracker.py, app/data_providers/snowplow/snowplow_corpus_slate_tracker.py, app/data_providers/snowplow/subject.py, app/data_providers/unleash_provider.py, app/data_providers/user_impression_cap_provider.py, app/data_providers/util.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, app/graphql/resolvers/corpus_slate_resolvers.py, app/graphql/resolvers/user_recommendation_preferences_resolvers.py, app/graphql/util.py, app/models/request_user.py, tests/functional/data_providers/test_unleash_provider.py, tests/functional/graphql/test_get_slate.py, tests/functional/graphql/test_get_slate_lineup.py, tests/functional/graphql/test_home_slate_lineup.py, tests/functional/graphql/test_setup_moment_slate.py, tests/functional/graphql/test_update_user_recommendation_preferences.py, tests/functional/graphql/test_user_reference_resolver.py, tests/mocks/user.py, tests/unit/data_providers/test_home_dispatch.py, tests/unit/data_providers/test_user_impression_cap_provider.py
Send the user locale to Unleash such that we can use an Unleash strategy to only assign certain locales to an experiment.
A product decision was made that [we can rely on the accept-language header](https://getpocket.atlassian.net/browse/HS-316?focusedCommentId=68493), which our GraphQL gateway sets as the ["gatewayLangauge" header](https://github.com/Pocket/client-api/blob/main/api-docs/docs/headers.md#web-repo-proxy-headers).
Tickets:
* https://getpocket.atlassian.net/browse/HS-353
- Rename `UserIds` to `RequestUser` now that it includes the user locale. The old name also made it seem like this was a collection of users, as opposed to multiple ids of a single user.
- Naming around locale/language is inconsistent: 'gatewayLangauge' in GraphQL and 'locale' in Unleash. I'm calling it …
=> feat(Home): Send locale to Unleash [HS-353]

Pipfile, Pipfile.lock, app/data_providers/slate_providers/pocket_hits_slate_provider.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, tests/unit/data_providers/test_pocket_hits_slate_provider.py
The publishing day for Pocket Hits slate on Home as displayed in the subheadline should start at 3am EDT.
Tickets:
* https://getpocket.atlassian.net/browse/HS-352
- The `pytz` library seems to be the conventional way in Python to get timezones. Python 3.9 introduces [zoneinfo](https://docs.python.org/3.9/library/zoneinfo.html#module-zoneinfo) that can replace this library.
=> fix(Home): Pocket Hits date was wrong [HS-352]

app/data_providers/dispatch.py
Log the Home user locale and experiment to find out why users are not getting assigned to the Home content v1 experiment.
Slack thread: https://pocket.slack.com/archives/C03QR6YN2HF/p1667414234636919
When locale=en-US:
> WARNING:root:User with locale=en-US was assigned to experiment: assigned=True name='temp.web.recommendation-api.home.contentv1' payload=None variant='treatment'
When locale is en-CA:
> WARNING:root:User with locale=en-CA was assigned to experiment: None
=> feat(Home): Log experiment outcome

app/graphql/util.py
Fix typo to correctly get the `gatewayLanguage` header.
=> fix(Home): Typo in gatewayLanguage header

buildspec.yml
Fix error that causes the [PR build to fail](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/996905175585/projects/RecommendationAPI-PRs-Prod/build/RecommendationAPI-PRs-Prod%3A5008e061-08b7-42e5-8f36-8bff66ec9c94/?region=us-east-1):
> ERROR: npm v9.1.1 is known not to run on Node.js v14.5.0.
Slack thread:
* https://pocket.slack.com/archives/C02JZ4TRF0S/p1668036357296579
=> fix(Build): ERROR: npm v9.1.1 is known not to run on Node.js v14.5.0.

app/graphql/syndicated_article.py
Fix graphql schema to provide syndicated article publisher URL to rec API
Not sure if it will work though, we might need to add `sharable` attribute to the original `SyndicateArticle` in `syndicated` subgraph https://www.apollographql.com/docs/federation/federated-types/federated-directives#shareable
=> Add publisher url to fedration key for syndicated article

app/data_providers/item2item.py, tests/functional/graphql/test_related.py
There should always be some recommendations displayed, even if the article was just added to the corpus and vectors store is not updated yet. Fallback to random syndicated or publisher articles.
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/TDP-108)
We could probably come up with something smarter for syndicated, like a filter by `save_count > 10000` but it will require adding another index on the pipeline side, so I don't want to overcomplicate it for now. Unfortunately, qdrant doesn' support ordering for the scroll method
=> Add fallback to random articles for related

app/data_providers/dispatch.py, app/data_providers/item2item.py, tests/functional/graphql/test_related.py
Add custom monitoring of how many errors and fallbacks we have in new related recommendations.
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/TDP-123)
I'm going to use logging parsing like it was done in Recit as the simplest solution. 
The proper approach of course would be to implement either [ structured logging](https://docs.aws.amazon.com/lambda/latest/operatorguide/parse-logs.html) or use a dedicated library for reporting custom application metrics.
=> Standardize logging of related recs

app/models/localemodel.py, tests/unit/models/test_locale_model.py
All users who prefer the German language should receive German Home, including locales such as `de-AT` (Austria).
Tickets:
* https://getpocket.atlassian.net/browse/TDP-270
- [corpus_slate_lineup_resolvers.py](https://github.com/Pocket/recommendation-api/blob/main/app/graphql/resolvers/corpus_slate_lineup_resolvers.py#L34) sets the default using `LocaleModel.from_string(locale, default=LocaleModel.en_US)`. `LocaleModel.from_string` now returns None if the `default` argument is not provided and the locale cannot be matched.
=> fix(Home): All users who prefer German should receive German Home [TDP-270]

app/data_providers/slate_providers/collection_slate_provider.py, tests/functional/graphql/test_home_slate_lineup.py
Fix broken link to explore more German Collections.
Tickets:
* https://getpocket.atlassian.net/browse/DIS-164
- Joel prefers to link to /collections and let the client redirect to the appropriate locale. I don't have a strong opinion either way, but the less client-specific logic that Recommendation API has to implement, the better. We might have to revisit this as new requirements come up when expanding to different markets.
=> fix(Home): German link for more collections is broken [DIS-164]

app/data_providers/item2item.py, tests/functional/graphql/test_related.py
Make sure all qdrant exceptions are always handled. Otherwise, it breaks the whole syndicated page.
=> Handle more qdrant calling exceptions

app/graphql/directives.py, app/graphql/item.py, app/graphql/syndicated_article.py
Move related recs caching to Apollo. Currently, not critical, but this will help to reduce the load on recAPI and vector store when firefox on-save and Android reader migration will be released.
I'm assuming here it will be cached on the Apollo server side. I don't completely understand how the whole thing works, so I might be wrong. I'll disable in-memory caching later if it works.
[Apollo docs](https://www.apollographql.com/docs/apollo-server/performance/caching/#using-with-federation)
[jira ticket](https://getpocket.atlassian.net/browse/TDP-304)
=> Add graphql caching for related

app/data_providers/dispatch.py, app/data_providers/item2item.py, app/graphql/item.py, app/graphql/resolvers/item2item_resolvers.py, app/graphql/syndicated_article.py, tests/functional/graphql/test_related.py
Fix a bug when related recommendations are displayed for a non-English item
[ticket](https://getpocket.atlassian.net/browse/TDP-327)
@mmiermans @bassrock Will apollo provide `language` field to recAPI as a part of federated key if it is not present in the client request? I assume yes.
[edit]: it seems apollo is unhappy with this. any ideas on how to work around and pull language?
@anthony-liddle FYI
=> Return empty recs for unsupported language

app/main.py
Improve latency by emitting telemetry only for a fraction of requests.
RecommendationAPI latency went up by about 30%:
Total request latency for Home went up by 20%.
Before:
After:
Tickets:
* https://getpocket.atlassian.net/browse/DIS-420
- I did not re-run a load test in Pocket-Dev because I wasn't able to see the latency increase in it before. Instead I'll monitor the production latency after deployment. I did confirm that we're now getting fewer traces in X-Ray.
=> fix(Telemetry): reduce latency by lowering rate [DIS-420]

app/config.py, app/data_providers/item2item.py, tests/functional/graphql/test_related.py
Split the Qdrant collection into two: all items and recommendation items with metadata.
This helps with the following:
- Search accuracy because ANN will work on 40k items instead of 1.5M
- Search performance (significantly fewer items to index)
- Easier deletion of outdated items
Related changes in the metaflow pipeline: https://github.com/Pocket/dl-metaflow-jobs/pull/174
Tickets:
- [Bug](https://getpocket.atlassian.net/browse/DIS-323)
- [Task](https://getpocket.atlassian.net/browse/DIS-398)
=> Split qdrant collection

app/data_providers/dispatch.py, app/data_providers/item2item.py
Fix syndicated page failure. Topic is optional for corpus items.
=> Remove qdrant topic usage

app/graphql/resolvers/corpus_slate_resolvers.py, app/models/corpus_recommendation_model.py, tests/functional/graphql/test_new_tab_slate.py
- Fix garbled argument descriptions in the GraphQL schema for newTabSlate.
- Fix error in tests. `region` should be provided, but can be null.
Before:
```graphql
newTabSlate(locale: String! = "<strawberry.arguments.StrawberryArgumentAnnotation object at 0x7f2bca05be50>", region: String = "<strawberry.arguments.StrawberryArgumentAnnotation object at 0x7f2bd96bb040>"): CorpusSlate!
```
After:
```graphql
newTabSlate(
"""
The Firefox build locale, for example 'fr-FR' or 'fr'. This determines which scheduled surface will be returned.
"""
locale: String!
"""
The geographic region, for example 'FR' or 'IT', or null if unavailable. This is currently not used, but will be used in the future to decide which scheduled surface to return when we serve multiple markets with the same language.
""" …
```
=> fix(NewTab): Argument descriptions were grabled

app/data_providers/feature_group/corpus_engagement_provider.py, app/data_providers/feature_group/feature_group_client.py, app/data_providers/slate_providers/new_tab_slate_provider.py, tests/functional/graphql/test_new_tab_slate.py, tests/functional/test_util/caching.py, tests/mocks/caching.py, tests/mocks/corpus_engagement_provider.py, tests/mocks/corpus_feature_group_client.py, tests/mocks/feature_store_mock.py, tests/unit/data_providers/conftest.py, tests/unit/data_providers/test_new_tab_slate_provider.py
- Rank New Tab recommendations for the new markets using Thompson sampling.
- Recommendations should be served successfully even when aggregate engagement data is not available.
Tickets:
* https://getpocket.atlassian.net/browse/DIS-456
In addition to the automated tests, I also tested that `newTabSlate` succeeds when the engagement Feature Group is unavailable.
Change the name of the Feature Group in `CorpusEngagementProvider`. The query successfully returns recommendations and the following error is logged:
> batch_get_record received 0 records and 47 errors. First error: {'FeatureGroupName': 'development-corpus-engagement-v123', 'RecordIdentifierValueAsString': 'NEW_TAB_EN_US/45f54436-46ea-5045-a753-f79a7e51c3ca/ffb9abaa-10d8-48c1-9afd-5bc8b3087353', 'ErrorCode': 'ValidationError', …
=> feat(NewTab): Add Thompson sampling [DIS-456]

.circleci/config.yml
Fix tests failing in CI because they can't connect to Snowplow Micro:
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='snowplow', port=9090): Max retries exceeded with url: /micro/reset
- The snowplow Docker container logs "No java installations was detected." and fails to start.
- Inside the Snowplow container Java says it has insufficient memory to start, despite that 6688 MB is available.
```
$ docker-compose exec snowplow java -Xmx2M -version
[0.002s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
```
- [Web/pull/4540](https://github.com/Pocket/Web/pull/4540) updated the [Snowplow Micro image](https://hub.docker.com/layers/pocket/snowplow-micro/latest/images/sha256-37b1 …
=> fix(CircleCI): Snowplow connection error

app/graphql/util.py, app/models/api_client.py
Prevent [an error](https://pocket.sentry.io/issues/4059757046/events/9466644d8d9e4a6ca9c0e77d42b71174/?environment=production&project=5503693&query=is%3Aunresolved&referrer=previous-event&stream_index=0) being logged when the synthetic API monitor makes a request without an `apiId`:
- The Snowplow tracker [checks that the api_client is truthy](https://github.com/Pocket/recommendation-api/blob/main/app/data_providers/snowplow/snowplow_corpus_recommendations_tracker.py#L65) before creating the Snowplow entity, so setting it to None will prevent the above error from being triggered.
- My initial thought was to put a check in the tracker `if event.api_client and event.api_client.api_id:` to avoid adding invalid data. Adding it to the Pydantic model seemed a better place, but I don't feel …
=> fix(Snowplow): Error when apiId header is missing

app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/life_hacks_slate_provider.py, app/data_providers/slate_providers/new_tab_slate_provider.py, app/data_providers/slate_providers/pocket_hits_slate_provider.py, app/data_providers/slate_providers/recommended_reads_slate_provider.py, app/data_providers/slate_providers/slate_provider.py, app/data_providers/slate_providers/topic_slate_provider.py, app/graphql/resolvers/corpus_slate_lineup_resolvers.py, app/graphql/resolvers/corpus_slate_resolvers.py, app/models/corpus_slate_lineup_model.py, app/models/localemodel.py, tests/unit/data_providers/test_new_tab_dispatch.py, tests/unit/data_providers/test_new_tab_slate_provider.py, tests/unit/models/test_locale_model.py
Return NewTab content for the 3 new markets based on the requested locale.
Tickets:
* https://getpocket.atlassian.net/browse/DIS-403
- Add a new class `HomeSlateProvider` to contain the Home translations. Those aren't relevant to NewTab.
=> feat(NewTab): Return content from new markets [DIS-403]

.aws/src/config/index.ts
Update elasticache node type to t3.micro from t2.micro which is no longer supported for reserved instance pricing
Tickets:[
* https://mozilla-hub.atlassian.net/browse/SE-3462
=> chore(elasticache): update elasticache node type to t3.micro

app/data_providers/dispatch.py, app/data_providers/unleash_provider.py, app/models/request_user.py
Being able to enroll in an experiment only users that are supported by the model
Tickets:
*[ Link to JIRA tickets](https://getpocket.atlassian.net/browse/DIS-756)
Use the existing `hasUserModel` strategy that was developed for recit. It works well here, the only downside that it says recit in property name.
=> Add support of hasUserModel Unleash strategy

.aws/src/monitoring.ts
Link the synthetic canary alarm to the corresponding runbook.
Tickets:
* https://getpocket.atlassian.net/browse/DIS-762
=> fix: Link Canary alarm to runbook

app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/recommended_reads_slate_provider.py, tests/functional/graphql/test_home_slate_lineup.py
1. Permanently integrate Thompson Sampling.
2. Enable sending events for the Hybrid Collaborative Filtering experiment.
The merge of this PR should be coordinated with @lfishhead and product folks + we'll need to configure `hasModelStrategy=hybrid_cf` in Unleash. Screenshots from dev of how it should look like:
Tickets:
* [Link to JIRA tickets](https://getpocket.atlassian.net/browse/DIS-605)
- This implementation of HybridCF provider does only impression capping without topic spreading and filtering by preferred topics.
=> Replace TS experiment with HybridCF

app/data_providers/dispatch.py
Add some logging to understand why some users were unexpectedly not enrolled in previous Thompson sampling experiments.
=> chore: Add logging to CF experiment

app/data_providers/unleash_provider.py, tests/functional/data_providers/test_unleash_provider.py
Some users are assigned to more than one treatment variant.
https://pocket.slack.com/archives/C02JZ4TRF0S/p1686265277754779?thread_ts=1686251034.146639&cid=C02JZ4TRF0S
One of the suspects is the presence of sessionId in the unleash call. We wanted to verify if that is helpful
Have you followed the guidelines in our Contributing document?
Tickets:
* Link to JIRA tickets
=> drop the sessionId from the unleash query

.aws/src/main.ts, .circleci/config.yml
Fix ratio memory/core after deployment reconfiguration. We anticipate the ML model that takes most of the space to grow in the next version. Also, I think it's better to be on the safe side and have lower memory utilization than 70%. The model is reloaded periodically and updated by metaflow. It can suddenly become slightly larger. Even though we have some checks for its size in the reloading code we do not want to end up with OOM, it's better to leave some buffer.
Also, update CI orb.
This is a copy of this PR https://github.com/Pocket/recommendation-api/pull/1049 which I couldn't land because of the unsigned commits.
=> Increase memory

app/data_providers/slate_providers/slate_provider.py, app/graphql/corpus_slate.py, app/models/corpus_slate_model.py, tests/unit/data_providers/test_new_tab_slate_provider.py
Return `utm_source` value per [API proposal](https://getpocket.atlassian.net/wiki/spaces/PE/pages/3000958977/NewTab+utm+source#utm_source-values). Analytics requires NewTab recommendation URLs to have a `utm_source` identifier that is unique per NewTab market.
Tickets:
* https://getpocket.atlassian.net/browse/DIS-803
=> feat(CorpusSlate): Add utm_source

app/data_providers/corpus/corpus_api_client.py, app/data_providers/slate_providers/new_tab_slate_provider.py, app/models/corpus_item_model.py, app/rankers/algorithms.py, tests/assets/engagement_metrics.py, tests/unit/data_providers/test_new_tab_slate_provider.py, tests/unit/models/test_corpus_item_model.py, tests/unit/rankers/test_algorithms.py
Replicate existing functionality from feed-machine to [boost syndicated articles](https://github.com/Pocket/feed-machine/blob/master/ranker.py#L143-L187) on NewTab.
- [Jira ticket DIS-845](https://getpocket.atlassian.net/browse/DIS-845)
- [Original project description and experiment results](https://docs.google.com/document/d/1Vgq63DZQF-pz7R3kvcNXgkUd1I829FZqkIUlpIVY_g4)
- [feed-machine implementation](https://github.com/Pocket/feed-machine/blob/master/ranker.py#L143-L187)
- The feed-machine implementation supported multiple slots, and different ways to select the syndicated article to be boosted. I simplified the code to a single slot, and the highest CTR item, because that's what we've used for the last few years.
=> feat(NewTab): Boost syndicated article to position 1

app/graphql/graphql_router.py, tests/functional/graphql/test_moz_social_slate.py
Add a test/demo endpoint for any future MozSocial client to consume and request new tab recommendations data.
Tickets:
* https://mozilla-hub.atlassian.net/browse/MC-33
Since we are just setting up a demo endpoint which returns the same query results as the new tab slate query, we've copied the existing implementation.
=> feat(mozsocialSlate): [MC-33] add demo endpoint for mozsocial slate

app/data_providers/corpus/corpus_api_client.py, tests/functional/data_providers/test_corpus_api_client.py
New Tab content should roll over at 3am local time, based on the timezone associated with the NewTab recommendation surface.
In the previous implementation, it incorrectly rolled over at midnight local time. This bug was introduced when migrating from the feed-machine to recommendation-api. Before the migration, content rolled over at 3am local time, as expected.
I added to the Firefox NewTab slate spec:
> Content rolls over at 3am local time.
* https://getpocket.atlassian.net/wiki/spaces/PE/pages/2927100008/Fx+NewTab+Slate+spec
Tickets:
* https://mozilla-hub.atlassian.net/jira/software/c/projects/MC/boards/720?modal=detail&selectedIssue=MC-76&assignee=64065e8893cf2599462fe21d
Slack thread:
> Carolyn: The stories you schedule for each day in the Curation Tool will start hitting New Tab at …
=> fix(NewTab): [MC-76] Content should roll over at 3am local time

Pipfile, Pipfile.lock
Fix [dependabot/77](https://github.com/Pocket/recommendation-api/security/dependabot/77).
```
for i in `seq 1 50`; do curl --location 'https://recommendation-api.getpocket.dev' --header 'Content-Type: application/json' --data '{
"query": "query NewTabSlate($locale: String!, $region: String, $count: Int) { newTabSlate(locale: $locale, region: $region) { id recommendations(count: $count) { id tileId corpusItem { id } } }}",
"variables": {"locale": "fr-FR", "region": "FR", "count": 30},
"operationName": "NewTabSlate"
}'; done
```
=> fix(Telemetry): Updated opentelemetry packages

app/data_providers/unleash_provider.py, tests/functional/data_providers/test_unleash_provider.py
When doing a gradual rollout we want to ensure that we have something we can be "sticky" against for a user.  Usually this is the userId, but if there is no user Id we need to use the sessionId or `guid`
=> fix(unleash): making unleash session sticky

app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/for_you_slate_provider.py, app/data_providers/slate_providers/life_hacks_slate_provider.py, app/data_providers/slate_providers/pockety_worthy_provider.py, app/data_providers/slate_providers/recommended_reads_slate_provider.py, app/rankers/algorithms.py, tests/unit/data_providers/test_for_you_slate_provider.py, tests/unit/rankers/test_algorithms.py
Ensure that for every request we apply thompson sampling but ensure that the content is the same for each user instead of constantly changing on page load.
=> feat(thompson-sampling): ensure thompson sampling is persistent based on user and day

app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/slate_providers/life_hacks_slate_provider.py, app/data_providers/slate_providers/pockety_worthy_provider.py, app/data_providers/slate_providers/recommended_reads_slate_provider.py
I noticed home was not showing completely new content. Digging in I realized only the for you slate actually had user impression capping on.
=> feat(capping): adding impression capping for each slate that supports it

app/graphql/resolvers/corpus_slate_resolvers.py, tests/functional/graphql/test_new_tab_slate.py
Allow `enableRankingByRegion` to be passed in to the `newTabSlate` query.
In a future PR we will optimize the recommendation order for the given region if this is set to True.
Tickets:
* [MC-1035](https://mozilla-hub.atlassian.net/browse/MC-1035)
Doc:
* [Experiment doc](https://docs.google.com/document/d/14SfGmWPwnzWv7oeDsHXZuRT-EUISEGqXCQmHRaoP6Lg/edit)
- I added a log message so we can check when this is successfully passed in once the change in firefox-api-proxy is merged.
[MC-1035]: https://mozilla-hub.atlassian.net/browse/MC-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [MC-1035] newTabSlate accepts enableRankingByRegion

app/data_providers/slate_providers/new_tab_slate_provider.py, tests/unit/data_providers/test_new_tab_slate_provider.py
* `MAX_TILE_ID` should be se to `(1 << 53) - 1`
* `tile_id` should be hashed from the `scheduled_surface_item_id`
* Copied over merino `tile_id` generation [test](https://github.com/mozilla-services/merino-py/pull/575/files#diff-60881568f1c11c653b36582c02f60d9256eba963b12c7876a0376721700c087bR360-R379) with the same values
Tickets:
* https://mozilla-hub.atlassian.net/browse/MC-1353
=> MC-1353: update tileId generation to match Merino

app/config.py, app/data_providers/dispatch.py, tests/unit/data_providers/test_for_you_slate_provider.py, tests/unit/data_providers/test_home_dispatch.py
Testing with an a/b test if/and how removing the syndication slate affects engagement
Flag: https://featureflags.readitlater.com/projects/default/features/temp.recommendation-api.pocket-home-no-syndication
=> feat(syndication): removing syndication as a test

app/config.py, app/data_providers/dispatch.py, app/data_providers/slate_providers/collection_slate_provider.py, app/data_providers/snowplow/snowplow_corpus_recommendations_tracker.py, app/data_providers/topic_provider.py, app/data_providers/translation.py, app/data_providers/user_recommendation_preferences_provider.py, app/graphql/resolvers/user_recommendation_preferences_resolvers.py, app/models/topic.py
It turns out when passing topic ids to the topic slate provider, you should be using the english ids, which then get merged with metadata from dynamodb, and our translations and then re-mapped into their real candidate set ids from the _TOPIC_CANDIDATE_SETS variables
I tested this locally against Prod.
This also puts all the extra locales behind an experiment feature flag.
=> fix(locales): updating the config to use the english ids for mapping

app/config.py, app/data_providers/dispatch.py, tests/functional/graphql/test_home_slate_lineup.py
The feature flag enrollment had a bug where we were not emitting enrollment events for those that were in the control group.
This makes the logic so that if the user is in one of the locale groups, and they are in the flag, we will emit an enrollment event.
=> fix(enrollment): updating enrollment to always send for locales

.circleci/config.yml
Fix deployment issue:
> This job was rejected because the image 'Remote Docker version: docker-20.10.18' is [unavailable](https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/)
[CircleCI Docker lifespan documentation](https://circleci.com/docs/remote-docker-images-support-policy/) says:
> We will support one version of Docker 20 with a tag of 20.10.24
Tickets:
* [MC-1550](https://mozilla-hub.atlassian.net/browse/MC-1550)
[MC-1550]: https://mozilla-hub.atlassian.net/browse/MC-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: upgrade remote docker image to 20.10.24
